@REM @echo off
@REM echo Running Nuxt Build...
@REM npm run generate

@REM echo Switching to Build Branch...
@REM git checkout build 2>nul || git checkout -b build

@REM echo Copying Built Files...
@REM robocopy dist . /E /MOVE > nul

@REM echo Staging Changes...
@REM git add .

@REM echo Committing Changes...
@REM git commit -m "Deploy: Auto-generated build"

@REM echo Pushing to Remote Build Branch...
@REM git push origin build --force

@REM echo Switching Back to Main Branch...
@REM git checkout -

@REM echo Done!
